services:
  web:
    container_name: control-center
    image: ghcr.io/vatsim-scandinavia/control-center:v6
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - sessions:/app/storage/framework/sessions
    environment:
      # Please check the complete configure guide for all variables and their description
      # You need to adjust this file to your needs
      - APP_NAME=Training Centre
      - APP_OWNER=Portugal vACC
      - APP_OWNER_SHORT=PTvACC
      - APP_OWNER_CODE=POR
      - APP_URL=https://cc.yourvacc.com
      - APP_ENV=production
      - DB_CONNECTION=sqlite
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=/Users/franciscog/IdeaProjects/controlcenter-PTvACC/database/database.sqlite
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_TABLE_PREFIX=
      - OAUTH_ID=yourIDhere
      - OAUTH_SECRET=yourSECREThere
      - VATSIM_BOOKING_API_TOKEN=yourTOKENhere
      - MAIL_HOST=127.0.0.1
      - MAIL_PORT=1025
      - MAIL_USERNAME=yourUSERNAMEhere
      - MAIL_PASSWORD=yourPASSWORDhere
      - MAIL_FROM_ADDRESS=noreply@yourvacc.com
volumes:
  sessions:
